spring.kafka.bootstrap-servers=${KAFKA_ADDRESS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.acks=all
server.port=3000
spring.datasource.url=${NLT_JDBC}
spring.datasource.username=${NLT_DB_USER}
spring.datasource.password=${NLT_DB_PASS}